### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by KirstieJane**
I've added Louise as a contributor to this repository - let me know if you think that's ok, or if anyone else should be added? @moreilly? me?

### CODE REVIEW

**Comment by KirstieJane** [comment]
DOH - I put this in the wrong place 😭 

Closing and I'll start again!

**Comment by MOReilly** [comment]
Hi,

Not sure how my email got added to this thread but I think you have the
wrong person. Can you remove me please?

Mick

**Comment by KirstieJane** [comment]
Oh no! I'm so sorry @MOReilly! Entirely my mistake - I meant @martintoreilly. I think the thread is closed so you shouldn't receive any other notifications after this apology.

**Comment by MOReilly** [comment]
No worries, thanks Kirstie!

**Pull request closed without merging**
